apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-eks.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  labels:
    io.kompose.service: pet-clinic-frontend-java
  name: pet-clinic-frontend-java
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: pet-clinic-frontend-java
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-eks.yml
        kompose.version: 1.27.0 (b0ed6a2c9)
      labels:
        io.kompose.service: pet-clinic-frontend-java
      annotations:
        sidecar.opentelemetry.io/inject-java: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://discovery-server:8761
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          image: public.ecr.aws/r9n6v8l1/springcommunity/spring-petclinic-api-gateway:latest
          env:
          - name: CONFIG_SERVER_URL
            value: http://config-server:8888
          - name: DISCOVERY_SERVER_URL
            value: http://discovery-server:8761/eureka
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          name: api-gateway-java
          ports:
            - containerPort: 8080
      restartPolicy: Always
status: {}
