AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  BillingInfoProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: ./src
      Policies:
        - DynamoDBCrudPolicy:
            TableName: BillingInfo
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:Scan
            Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/BillingInfo"
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
            Resource: "*"
      Environment:
        Variables:
          TABLE_NAME: BillingInfo
      Timeout: 60
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /process-billing
            Method: get

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "billing-info-bucket-${AWS::Region}-${AWS::AccountId}"

Outputs:
  BillingInfoProcessorFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt BillingInfoProcessor.Arn

  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/process-billing"

  S3BucketName:
    Description: "S3 bucket name for storing artifacts"
    Value: !Ref S3Bucket
